name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-wheel openjdk-17-jdk android-sdk-platform-tools android-sdk-build-tools android-ndk

      - name: Install Buildozer and dependencies
        run: |
          pip install buildozer
          [ -f requirements.txt ] && pip install -r requirements.txt

      - name: Initialize Buildozer
        run: buildozer init

      - name: Display buildozer.spec
        run: cat buildozer.spec

      - name: Modify buildozer.spec (optional)
        run: |
          sed -i 's/^title = .*/title = MyApp/' buildozer.spec
          sed -i 's/^package.name = .*/package.name = myapp/' buildozer.spec
          sed -i 's/^requirements = .*/requirements = kivy, requests/' buildozer.spec

      - name: Build APK
        run: |
          buildozer android clean
          buildozer -v android debug

      - name: Debug files
        run: ls -la bin/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk
          if-no-files-found: error
